NZPost.VoucherService.Admin/Controllers/BatchController.cs
using NZPost.VoucherService.Admin.ViewModel;
using NZPost.VoucherService.AppServices;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NZPost.VoucherService.Admin.Controllers
{
    public class BatchController : Controller
    {
        private BatchService batchService;
        private OrganisationService organisationService;
        private DepartmentService departmentService;
        private CampaignService campaignService;

        public BatchController(BatchService batchService, OrganisationService organisationService, DepartmentService departmentService, CampaignService campaignService)
        {
            this.batchService = batchService;
            this.organisationService = organisationService;
            this.departmentService = departmentService;
            this.campaignService = campaignService;
        }
      
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create()
        {
            BatchViewModel vm = new BatchViewModel();
            vm.Organisations = organisationService.GetAllActiveOrganisations();
            vm.Departments = departmentService.GetAllDepartments();
            vm.Campaigns = campaignService.GetAllCampaigns();
            return View(vm);
        }

    }
}

NZPost.VoucherService.Admin/Controllers/HomeController.cs
using NZPost.VoucherService.AppServices;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NZPost.VoucherService.Admin.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        private OrganisationService organisationService;
      
        public HomeController (OrganisationService organisationService)
        {
            this.organisationService = organisationService; 
        }
        public ActionResult Index()
        {
           // ViewBag.Message = organisationService.GetAllActiveOrganisations().First().Name;

            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your app description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

NZPost.VoucherService.Admin/Controllers/UserMaintenanceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NZPost.VoucherService.Admin.Controllers
{
    public class UserMaintenanceController : Controller
    {
        //
        // GET: /UserMaintenance/

        public ActionResult Index()
        {
            return View();
        }

    }
}

NZPost.VoucherService.Admin/Views/Batch/Create.cshtml
@model NZPost.VoucherService.Admin.ViewModel.BatchViewModel
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create Batch</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>BatchViewModel</legend>
        <div class="editor-label">
            @Html.Label("Organisation")
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model=>model.OrganisationIdForSearch,new SelectList(Model.Organisations,"Id","name"),"Please select") 
            @Html.ValidationMessageFor(model => model.OrganisationIdForSearch)          
        </div>
        <div class="editor-label">
            @Html.Label("Department")
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.DepartmentIdForSearch, new SelectList(Model.Departments, "Id", "name"), "Please select")
            @Html.ValidationMessageFor(model => model.DepartmentIdForSearch)
        </div>
        <div class="editor-label">
            @Html.Label("Campaign")
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.CampaignIdForSearch, new SelectList(Model.Campaigns, "Id", "name"), "Please select")
            @Html.ValidationMessageFor(model => model.CampaignIdForSearch)
        </div>
        <div class="editor-label">
            @Html.Label("Batch Name")
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.BatchName)
            @Html.ValidationMessageFor(model => model.BatchName)
        </div>

        <div class="editor-label">
            @Html.Label("Batch Description")
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.BatchDesc)           
        </div>

        <div class="editor-label">
            @Html.Label("Number Of Vouchers")
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.NoOfVouchers)
            @Html.ValidationMessageFor(model => model.NoOfVouchers)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NZPost.VoucherService.Admin/Views/Batch/Index.cshtml
@model NZPost.VoucherService.Admin.ViewModel.BatchViewModel

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>BatchViewModel</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.BatchName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.BatchName)
            @Html.ValidationMessageFor(model => model.BatchName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.BatchDesc)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.BatchDesc)
            @Html.ValidationMessageFor(model => model.BatchDesc)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.NoOfVouchers)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.NoOfVouchers)
            @Html.ValidationMessageFor(model => model.NoOfVouchers)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NZPost.VoucherService.Admin/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<article>
    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>
</article>

<aside>
    <h3>Aside Title</h3>
    <p>
        Use this area to provide additional information.
    </p>
    <ul>
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("About", "About", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
    </ul>
</aside>

NZPost.VoucherService.Admin/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<section class="contact">
    <header>
        <h3>Phone</h3>
    </header>
    <p>
        <span class="label">Main:</span>
        <span>425.555.0100</span>
    </p>
    <p>
        <span class="label">After Hours:</span>
        <span>425.555.0199</span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Email</h3>
    </header>
    <p>
        <span class="label">Support:</span>
        <span><a href="mailto:Support@example.com">Support@example.com</a></span>
    </p>
    <p>
        <span class="label">Marketing:</span>
        <span><a href="mailto:Marketing@example.com">Marketing@example.com</a></span>
    </p>
    <p>
        <span class="label">General:</span>
        <span><a href="mailto:General@example.com">General@example.com</a></span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Address</h3>
    </header>
    <p>
        One Microsoft Way<br />
        Redmond, WA 98052-6399
    </p>
</section>

NZPost.VoucherService.Admin/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                @*<h1>@ViewBag.Title.</h1>
                <h2>@ViewBag.Message</h2>*@
                <h1>Voucher Service</h1>
            </hgroup>
            @*<p>
                To learn more about ASP.NET MVC visit
                <a href="http://asp.net/mvc" title="ASP.NET MVC Website">http://asp.net/mvc</a>.
                The page features <mark>videos, tutorials, and samples</mark> to help you get the most from ASP.NET MVC.
                If you have any questions about ASP.NET MVC visit
                <a href="http://forums.asp.net/1146.aspx/1?MVC" title="ASP.NET MVC Forum">our forums</a>.
            </p>*@
        </div>
    </section>
}

<p>@Html.ActionLink("Create Batch", "Create", "Batch")</p>
<p>@Html.ActionLink("Search Batch", "actionName", "ControllerName")</p>
<p>@Html.ActionLink("Organisation Maintenance", "actionName", "ControllerName")</p>
<p>@Html.ActionLink("Department Maintenance", "actionName", "ControllerName")</p>
<p>@Html.ActionLink("Campaign Maintenance", "actionName", "ControllerName")</p>
<p>@Html.ActionLink("User Maintenance", "actionName", "ControllerName")</p>
<p>@Html.ActionLink("Voucher Maintenance", "actionName", "ControllerName")</p>
@*<h3>We suggest the following:</h3>
<ol class="round">
    <li class="one">
        <h5>Getting Started</h5>
        ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
        enables a clean separation of concerns and that gives you full control over markup
        for enjoyable, agile development. ASP.NET MVC includes many features that enable
        fast, TDD-friendly development for creating sophisticated applications that use
        the latest web standards.
        <a href="http://go.microsoft.com/fwlink/?LinkId=245151">Learn more…</a>
    </li>

    <li class="two">
        <h5>Add NuGet packages and jump-start your coding</h5>
        NuGet makes it easy to install and update free libraries and tools.
        <a href="http://go.microsoft.com/fwlink/?LinkId=245153">Learn more…</a>
    </li>

    <li class="three">
        <h5>Find Web Hosting</h5>
        You can easily find a web hosting company that offers the right mix of features
        and price for your applications.
        <a href="http://go.microsoft.com/fwlink/?LinkId=245157">Learn more…</a>
    </li>
</ol>*@

NZPost.VoucherService.Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">

                    <a href='@Url.Action("Index", "Home")'>
                        <img src='@Url.Content("~/Images/NZPost_Logo.png")' />
                    </a>


                    @*<img src="~/Images/NZPost_Logo.png"  />
                    <p class="site-title">@Html.ActionLink("your logo here", "Index", "Home")</p>*@
                </div>
                <div class="float-right">
                    <section id="login">
                       Hello, <span class="username">@User.Identity.Name</span>!
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - NZ Post</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>